_BASE_: Base-YouTubeVIS-VideoInstanceSegmentation.yaml
MODEL:
  WEIGHTS: "model_final_3c8ec9.pkl"
  META_ARCHITECTURE: "MinVIS"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 40
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_minvis"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
      WINDOW_INFERENCE: True
      WINDOW_SIZE: 3

SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.0001
  STEPS: (14000,)
  MAX_ITER: 20000
  WARMUP_FACTOR: 1.0
  WARMUP_ITERS: 10
  WEIGHT_DECAY: 0.05

INPUT:
  MIN_SIZE_TRAIN: (240, 360, 480)
  MAX_SIZE_TRAIN: 768
  MIN_SIZE_TEST: 360
  SAMPLING_FRAME_NUM: 1

  SAMPLING_FRAME_SHUFFLE: False
  # MIN_SIZE_TRAIN_SAMPLING : ["range", "choice", "range_by_clip", "choice_by_clip"]
  MIN_SIZE_TRAIN_SAMPLING: "choice_by_clip"
  # RANDOM_FLIP : ["none", "horizontal", "flip_by_clip"]. "horizontal" is set by default.
  RANDOM_FLIP: "flip_by_clip"
  AUGMENTATIONS: []
  CROP:
    ENABLED: True
    TYPE: "absolute_range"
    SIZE: (384, 600)
  # For pseudo videos
  PSEUDO:
    AUGMENTATIONS: ['rotation']
    MIN_SIZE_TRAIN: (240, 360, 480)
    MAX_SIZE_TRAIN: 768
    CROP:
      ENABLED: True
      TYPE: "absolute_range"
      SIZE: (384, 600)
  LSJ_AUG:
    ENABLED: False
    IMAGE_SIZE: 768
    MIN_SCALE: 0.1
    MAX_SCALE: 2.0

DATASETS:
  DATASET_NEED_MAP: [True, False, ]
  DATASET_TYPE: ['image_instance', 'video_instance', ]
  DATASET_TYPE_TEST: ['video_instance', ]
  # The categories of all datasets will be mapped to the categories of the last dataset
  DATASET_RATIO: [1.0, 0.75]
  TRAIN: ("coco2ytvis2019_train", "ytvis_2019_train")
  TEST: ("ytvis_2019_val",)

DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True

OUTPUT_DIR: './output_MinVIS_R50_YTVIS19'