_BASE_: Base-VSPW-VideoInstanceSegmentation.yaml

MODEL:
  WEIGHTS: "model_final_3c8ec9.pkl"
  META_ARCHITECTURE: "MinVIS"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 124
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_minvis"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    CLASS_WEIGHT: 2.0
    MASK_WEIGHT: 5.0
    DICE_WEIGHT: 5.0
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    PRE_NORM: False
    ENFORCE_INPUT_PROJ: False
    SIZE_DIVISIBILITY: 32
    DEC_LAYERS: 10  # 9 decoder layers, add one for the loss on learnable query
    TRAIN_NUM_POINTS: 12544
    OVERSAMPLE_RATIO: 3.0
    IMPORTANCE_SAMPLE_RATIO: 0.75
    TEST:
      OVERLAP_THRESHOLD: 0.8
      OBJECT_MASK_THRESHOLD: 0.8
      WINDOW_INFERENCE: True
      WINDOW_SIZE: 3
SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (14000,)
  MAX_ITER: 20000
INPUT:
  SAMPLING_FRAME_NUM: 1
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  RANDOM_FLIP: "flip"
  AUGMENTATIONS: []
  MIN_SIZE_TRAIN: (288, 320, 352, 384, 416, 448, 480, 512, 544, 576, 608, 640)
  MIN_SIZE_TEST: 480
  FORMAT: "RGB"

DATASETS:
  DATASET_RATIO: [1.0, ]
  DATASET_NEED_MAP: [False, ]
  DATASET_TYPE: ['video_semantic', ]
  DATASET_TYPE_TEST: ['video_semantic', ]
  # The categories of all datasets will be mapped to the categories of the last dataset
  TRAIN: ("VSPW_vss_video_train",)
  TEST: ("VSPW_vss_video_val",)

OUTPUT_DIR: './output_MinVIS_R50_480p_VSPW'

